version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 10
      semver-major-days: 14
      semver-minor-days: 10
      semver-patch-days: 7
